#コマンドのプレフィックス
Prefix: '&bLite&3SignIn &f&l>>> '

#プラグインの言語
#使用可能: Japanese, English, Simplified-Chinese, Traditional-Chinese
Language: Japanese

#PlaceholderAPI 設定
PlaceholderAPI:
    #PlaceholderAPIを使用するかどうか
    Enabled: true
    #プレースホルダーキャッシュの更新のレイテンシー（秒）
    #一部のプレースホルダーはデータベースのデータを継続的に読み取る必要があるため、
    #このオプションは、PAPIプレースホルダーへの頻繁な呼び出しによって引き起こされるデータベースIOの大きな負担を防ぐために使用されます。
    Cache-Update-Delay: 10
    #例外のプレースホルダー（キャッシュされません）
    #例: 'queue' は %litesignin_queue% 
    Exceptions: [] 

#毎日のオンライン時間の条件（プレイヤーはオンライン時間が一定時間に達してからサインイン必要がある）
#注：サーバの再起動やプラグインのアンインストールにより、今日のオンライン時間の統計がリセットされます。
Online-Duration-Condition:
    #有効かどうか
    Enabled: false
    #必要な時間
    #書式：時：分：秒、左から右へ
    #最小: 00:00:00 、 最大: 23:59:59
    Time: 00:03:00
    #統計を取るかどうか（有効にすると、プレイヤーが途中で切断しても、今日のオンライン時間は保持されます）
    Statistics: true
    
#プレイヤーが以下のリストの世界にいる場合、サインインは使用できません
Disabled-Worlds: []

#サインインランキング機能を有効にするかどうか
#この機能は、毎日サインインするプレイヤーの順番を登録するために使用されます。
Enable-Sign-In-Ranking: true

#マルチグループ報酬モードを有効にするかどうか
#プレーヤーが同時に異なるグループからの複数の権限を持っている場合、チェックイン時に同時に報酬を受け取ります
#たとえば、Group1とGroup2の両方のグループ権限を持つプレーヤーは、サインイン後に両方のグループから報酬を受け取ります。
Enable-Multi-Group-Reward: false

#サーバーに入るときにサインインするようにプレーヤーに通知するかどうか
Join-Event:
    Enabled: true
    #自動サインインを有効にするかどうか（許可が必要）
    Auto-SignIn: false
    #遅延（単位：秒）
    Delay: 0

#メニュー関連設定
GUI-Settings:
    #GUIをメニューとして有効にするかどうか
    Enabled: true
    #下限の日。これより前の日付は無効になります。
    #PS: 2019/11/15/ は最初のバージョンがリリースされた日です
    Limit-Date:
        Enabled: false
        #最小年
        Minimum-Year: 2019
        #最大年
        Minimum-Month: 11

#更新を自動的にチェックするかどうか
#サーバーが起動するたびに実行され、新しいバージョンが見つかったときに管理者に通知します。
#この機能により、サーバーが生成するトラフィックが多すぎることはありません（毎回約1kb）
Updater: true

#データを自動的に保存する
Auto-Save: 
    #有効と無効
    Enabled: false
    #MySQLモードでのみ有効にするかどうか
    Only-MySQL: true
    #冷却時間（分）
    Delay: 10
    
#Metricsを有効にするかどうか
#詳細については、https://bstats.org/plugin/bukkit/LiteSignIn/11849 を参照してください。
Metrics: true
    
#木の看板サインインスクリプト
#有効にすると、WoodSignSettings.ymlファイルが生成されます。中のこの記事のメモに従って編集してください。
Wood-Signs-Script: false

#非同期スレッドの設定
#非同期スレッドが何であるかわからない場合は、このオプションを変更しないでください!
Async-Thread-Settings: 
    #タスク スレッドの遅延、主に提出された新しいタスクを処理します
    Task-Thread-Delay: 0.1
    #非同期タスクの設定
    #特定のタスクを非同期タスクとして設定することを選択できます。
    Async-Task-Settings:
        #リーダーボード ビュー (コマンド /litesignin leaderboard)
        Leaderboard-View: false
        #プレイヤーのデータを読み込む
        Load-Data: true
        #GUI を開く (ヘッドをロードすると遅延が発生する可能性があるため、このオプションはデフォルトで有効になっています)
        Open-GUI: true
    
#遡及カード
#過去の日を補うためにそれを使用してす
Retroactive-Card:
    #有効と無効
    Enabled: true
    #冷却時間（分）
    Intervals: 5
    #必要な数量
    Quantity-Required: 1
    #下限の日。これより前の日付は無効になります。
    #PS: 2019/11/15/ は最初のバージョンがリリースされた日です
    Minimum-Date: '2019-11-15'
    #必要なもの
    Required-Item:
        #「false」の場合、カードはデータになります。 それ以外の場合は、ゲームのインベントリに配置できるアイテムになります。
        Enabled: false
        #アイテムの名
        #CustomItems.ymlファイルで編集できます。
        CustomItem: 'RetroactiveCard'

#MySQL データベース設定
MySQL-Storage:
    #有効と無効
    Enabled: false
    #ホスト名
    Hostname: localhost
    #ポート
    Port: 3306
    #ユーザー名
    Username: 'root'
    #パスワード
    Password: 'password'
    #データベースの名
    Database: 'litesignin'
    #更新の冷却時間
    Refresh-Interval: 5
    #接続タイムアウト時間
    Wait-Timeout: 18000
    #データシート名
    Table-Name: playerdata
    #自動配置モード
    #このモードでは、MySQLに接続すると自動的にターゲット・データベースを検索/作成します
    #これは、導入はできてもMySQLを操作できない人にのみ使用できます。
    #PS：サーバがターゲットデータベースにアンカーできない場合は、このオプションをオフにして手動でデータベースを作成する必要があります！
    Automatic-Deploy-Mode: true
    #その他の接続パラメータ。 もし君は開発者ではなく、またはJDBCに精通していない、このオプションを変更しないでください。
    Options:
        useSSL: false
        useUnicode: true
        allowMultiQueries: true
        allowPublicKeyRetrieval: true
        characterEncoding: 'utf8'
        autoReconnect: true
    
#SQLite データベース設定
#ストレージモードの優先度: Yaml < SQLite < MySQL
SQLite-Storage:
    #有効と無効
    Enabled: true
    #データベースの名
    Database-File: 'Database.db'
    #フォルダパス
    Database-Path: 'plugins/LiteSignIn/'
    #更新の冷却時間
    Refresh-Interval: 5
    #データシート名
    Table-Name: playerdata
    
#データベース管理
Database-Management:
    #バックアップ
    Backup:
        #有効と無効
        Enabled: true
        #自動バックアップを有効にするかどうか（サーバーがシャットダウンされるたびに自動実行されます）
        Auto-Backup: false
        #フォルダパス
        Backup-Folder-Path: 'plugins/LiteSignIn/Backup/'
        #バックアップファイルの名
        Backup-File: 'Backup-{time}'
        #時間書式
        Time-Format: 'yyyy-MM-dd-HH-mm-ss'
    #ロールバック
    Rollback:
        #有効と無効
        Enabled: true
        #バックアップファイルの名（バックアップフォルダのパスと一致している必要があります）
        Backup-Folder-Path: 'plugins/LiteSignIn/Backup/'
        #ロールバックを実行する前にバックアップを作成するかどうか
        Rollback-With-Backup: true
    
#サインインするとき、タスクの実行順序
Reward-Task-Sequence:
- ITEMS_REWARD
- COMMANDS_EXECUTION
- MESSAGES_SENDING
- BROADCAST_MESSAGES_SENDING
- PLAYSOUNDS

#権限設定
#Defaultがtrueの場合、デフォルトで全員に権限があります。
Permissions:
    #遡及カード関連
    Retroactive-Card:
        #使用
        Use:
            Permission: signin.retroactive-card.use
            Default: true
        #この許可がない場合、システムは自動的にカードを没収します
        Hold:
            Permission: signin.retroactive-card.hold
            Default: true
    #自動更新関連
    Updater: 
        Permission: signin.updater
        Default: false
    #自動サインインの権限
    Join-Auto-SignIn:
        Default: false
        Permission: signin.joinevent.autosignin
    Disabled-Worlds-Bypass:
        Default: false
        Permission: signin.bypass
    #コマンド関連の権限
    Commands:
        Help: 
            Permission: signin.command.help
            Default: true
        Reload: 
            Permission: signin.command.reload
            Default: false
        GUI: 
            Permission: signin.command.gui
            Default: true
        Designated-GUI: 
            Permission: signin.command.designatedgui
            Default: false
        Click: 
            Permission: signin.command.click
            Default: true
        Click-Others: 
            Permission: signin.command.clickothers
            Default: false
        Info: 
            Permission: signin.command.info
            Default: false
        RetroactiveCard:
            Permission: signin.command.retroactivecard
            Default: false
            Give:
                Permission: signin.command.retroactivecard.give
                Default: false
            Set:
                Permission: signin.command.retroactivecard.set
                Default: false
            Take:
                Permission: signin.command.retroactivecard.take
                Default: false
        ItemCollection: 
            Permission: signin.command.itemcollection
            Default: false
            List:
                Permission: signin.command.itemcollection.list
                Default: false
            Add:
                Permission: signin.command.itemcollection.add
                Default: false
            Delete:
                Permission: signin.command.itemcollection.delete
                Default: false
            Give:
                Permission: signin.command.itemcollection.give
                Default: false
        Save: 
            Permission: signin.command.save
            Default: false
        Database:
            Permission: signin.command.database
            Default: false
            Backup:
                Permission: signin.command.database.backup
                Default: false
            Rollback:
                Permission: signin.command.database.rollback
                Default: false
        LeaderBoard:
            Permission: signin.command.leaderboard
            Default: true
            Designated-Date:
                Permission: signin.command.leaderboard.designateddate
                Default: false
        Reward:
            Permission: signin.command.reward
            Default: false